---
title: "TDK web scraping"
author: "Dittrich Levente"
date: "`r Sys.Date()`"
output:
  html_document:
    toc:true
    toc_float:true
---

# Libraries and the header file

```{r setup, message=FALSE}
# data transform, etc
library(tidyverse)

# scraping
library(rvest)
library(httr)

# translating
library(deeplr)

# financial data
library(quantmod)
```

```{r}
# functions
source("webscrape_full_text.R")
```

# Links for the scraping

```{r}
varga_link = "https://hang.hu/kereses/cimke/varga-mihaly-660"

kinfo_link = "https://hang.hu/kereses/cimke/kormanyinfo-1462"
nagy_link = "https://hang.hu/kereses/cimke/nagy-marton-27845"
matolcsy_link = "https://hang.hu/kereses/cimke/matolcsy-gyorgy-631"
```

# Scraping

```{r echo=FALSE}
# OK
varga = scrape_magyar_hang(varga_link)
varga$name = "varga"

# OK - de sok a belfoldes kinfo cikk
kinfo = scrape_magyar_hang(kinfo_link)
kinfo$name = "kinfo"

# OK
nagy = scrape_magyar_hang(nagy_link)
nagy$name = "nagy"

# OK
matolcsy = scrape_magyar_hang(matolcsy_link)
matolcsy$name = "matolcsy"
```

# Aggregating data

```{r}
full_dataset = rbind(
  varga,
  nagy,
  matolcsy,
  kinfo
)
```

# Translating to English

We are using Deepl API Pro
```{r}
api_key = readLines("deepl_api_key.txt")

# making an empty col for the translated text
full_dataset$text_eng = NA

# iterating trough the dataset and translating the articles
for (i in 1:nrow(full_dataset)) {
  
  # translating
  text_eng = translate(text = full_dataset$text[i],
                        source_lang = "HU",
                        target_lang = "EN",
                        auth_key = api_key)
  
  # saving the translation to the df
  full_dataset$text_eng[i] = text_eng
  
  # Sys.sleep(5)
}
```

# Making the full dataset

```{r}
ir = read.csv("alapkamatok.csv")

eur = getSymbols("EURHUF=X", from = "2018-06-01", to="2025-02-14", auto.assign = F) %>%
  as.data.frame() %>% 
  rename(eur_close = `EURHUF=X.Close`) %>% 
  mutate(Date = row.names(.)) %>% 
  select(Date, eur_close) %>% 
  left_join(ir, by = "Date") %>%
  fill(Fed, MNB, ECB, .direction = "downup") %>% 
  select(-X)

articles = read.csv("D://TDK-Eur-Huf/Sentiment analysis/articles_tranlated_w_sentiment.csv")

articles_wide = articles %>% 
  select(date, name, title,  prediction) %>% 
  group_by(date, name) %>% 
  summarise(mean = mean(prediction),
            max = max(prediction)) %>% 
  pivot_wider(values_from = c("mean", "max")) %>% 
  rename(Date = date)

df = eur %>% 
  left_join(articles_wide, by = "Date") %>%
  na.fill(0) %>% 
  as.data.frame()

write.csv(df, "full_dataset.csv")
```

